// Generated by gencpp from file beginner_tutorials/ModifyText.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MODIFYTEXT_H
#define BEGINNER_TUTORIALS_MESSAGE_MODIFYTEXT_H

#include <ros/service_traits.h>


#include <beginner_tutorials/ModifyTextRequest.h>
#include <beginner_tutorials/ModifyTextResponse.h>


namespace beginner_tutorials
{

struct ModifyText
{

typedef ModifyTextRequest Request;
typedef ModifyTextResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModifyText
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::ModifyText > {
  static const char* value()
  {
    return "2ea50b9bce33ae6fad63d90c193917b0";
  }

  static const char* value(const ::beginner_tutorials::ModifyText&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::ModifyText > {
  static const char* value()
  {
    return "beginner_tutorials/ModifyText";
  }

  static const char* value(const ::beginner_tutorials::ModifyText&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::ModifyTextRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::ModifyText >
template<>
struct MD5Sum< ::beginner_tutorials::ModifyTextRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::ModifyText >::value();
  }
  static const char* value(const ::beginner_tutorials::ModifyTextRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::ModifyTextRequest> should match
// service_traits::DataType< ::beginner_tutorials::ModifyText >
template<>
struct DataType< ::beginner_tutorials::ModifyTextRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::ModifyText >::value();
  }
  static const char* value(const ::beginner_tutorials::ModifyTextRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::ModifyTextResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::ModifyText >
template<>
struct MD5Sum< ::beginner_tutorials::ModifyTextResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::ModifyText >::value();
  }
  static const char* value(const ::beginner_tutorials::ModifyTextResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::ModifyTextResponse> should match
// service_traits::DataType< ::beginner_tutorials::ModifyText >
template<>
struct DataType< ::beginner_tutorials::ModifyTextResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::ModifyText >::value();
  }
  static const char* value(const ::beginner_tutorials::ModifyTextResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MODIFYTEXT_H
