// Generated by gencpp from file beginner_tutorials/modifyText.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MODIFYTEXT_H
#define BEGINNER_TUTORIALS_MESSAGE_MODIFYTEXT_H

#include <ros/service_traits.h>


#include <beginner_tutorials/modifyTextRequest.h>
#include <beginner_tutorials/modifyTextResponse.h>


namespace beginner_tutorials
{

struct modifyText
{

typedef modifyTextRequest Request;
typedef modifyTextResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct modifyText
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::modifyText > {
  static const char* value()
  {
    return "2ea50b9bce33ae6fad63d90c193917b0";
  }

  static const char* value(const ::beginner_tutorials::modifyText&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::modifyText > {
  static const char* value()
  {
    return "beginner_tutorials/modifyText";
  }

  static const char* value(const ::beginner_tutorials::modifyText&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::modifyTextRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::modifyText >
template<>
struct MD5Sum< ::beginner_tutorials::modifyTextRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::modifyText >::value();
  }
  static const char* value(const ::beginner_tutorials::modifyTextRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::modifyTextRequest> should match
// service_traits::DataType< ::beginner_tutorials::modifyText >
template<>
struct DataType< ::beginner_tutorials::modifyTextRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::modifyText >::value();
  }
  static const char* value(const ::beginner_tutorials::modifyTextRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::modifyTextResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::modifyText >
template<>
struct MD5Sum< ::beginner_tutorials::modifyTextResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::modifyText >::value();
  }
  static const char* value(const ::beginner_tutorials::modifyTextResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::modifyTextResponse> should match
// service_traits::DataType< ::beginner_tutorials::modifyText >
template<>
struct DataType< ::beginner_tutorials::modifyTextResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::modifyText >::value();
  }
  static const char* value(const ::beginner_tutorials::modifyTextResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MODIFYTEXT_H
