// Generated by gencpp from file beginner_tutorials/ModifyTextRequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MODIFYTEXTREQUEST_H
#define BEGINNER_TUTORIALS_MESSAGE_MODIFYTEXTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct ModifyTextRequest_
{
  typedef ModifyTextRequest_<ContainerAllocator> Type;

  ModifyTextRequest_()
    : inputString()  {
    }
  ModifyTextRequest_(const ContainerAllocator& _alloc)
    : inputString(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _inputString_type;
  _inputString_type inputString;





  typedef boost::shared_ptr< ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ModifyTextRequest_

typedef ::beginner_tutorials::ModifyTextRequest_<std::allocator<void> > ModifyTextRequest;

typedef boost::shared_ptr< ::beginner_tutorials::ModifyTextRequest > ModifyTextRequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::ModifyTextRequest const> ModifyTextRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator2> & rhs)
{
  return lhs.inputString == rhs.inputString;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "998e350d95d4a84f3e250cb220ede566";
  }

  static const char* value(const ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x998e350d95d4a84fULL;
  static const uint64_t static_value2 = 0x3e250cb220ede566ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/ModifyTextRequest";
  }

  static const char* value(const ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"string inputString\n"
;
  }

  static const char* value(const ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.inputString);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModifyTextRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::ModifyTextRequest_<ContainerAllocator>& v)
  {
    s << indent << "inputString: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.inputString);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MODIFYTEXTREQUEST_H
